/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package protoipo.UI;

import Fachada.Fachada;
import java.io.File;
import java.util.Enumeration;
import java.util.InputMismatchException;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.ButtonModel;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import prototipo.Utilitario.FileChooser;
import prototipo.Utilitario.*;

/**
 *
 * @author Deibys
 */
public class IUEgresosC extends javax.swing.JInternalFrame {

    /**
     * Creates new form IUEgresosC
     */
    private Fachada fachada = null;
    public IUEgresosC(IUMenuPrincipal principal, Fachada pFachada) {
        super("", true,true,false,true);
        setPanelPrincipal(principal);    
        fachada = pFachada;
        initComponents();       
        this.jBt_Ingresar.setVisible(true);
        fileChooser = new FileChooser();
        
        
        panelInterno2 = new jPEgreso2(this, fachada);
        panelInterno2.setBackground(new java.awt.Color(255, 255, 255));
        panelInterno2.setBounds(0, 0, 690, 470);
        panelEnCapas.add(panelInterno2);
        panelEnCapas.moveToBack(panelInterno2);
        panelInterno2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bG_Motivo = new javax.swing.ButtonGroup();
        bG_Ingreso = new javax.swing.ButtonGroup();
        panelEnCapas = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jLb_motivo = new javax.swing.JLabel();
        jLb_Titulo = new javax.swing.JLabel();
        jRb_Ventas = new javax.swing.JRadioButton();
        jRb_Muertes = new javax.swing.JRadioButton();
        jRb_Perdidas = new javax.swing.JRadioButton();
        jRb_Otros = new javax.swing.JRadioButton();
        jLb_ingPor = new javax.swing.JLabel();
        jRb_Archivo = new javax.swing.JRadioButton();
        jRb_Manual = new javax.swing.JRadioButton();
        jBt_Ingresar = new javax.swing.JButton();

        setTitle("Egresos");

        panelEnCapas.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLb_motivo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLb_motivo.setText("Motivo");

        jLb_Titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLb_Titulo.setForeground(new java.awt.Color(51, 0, 204));
        jLb_Titulo.setText("EGRESO DE CARAVANAS");

        bG_Motivo.add(jRb_Ventas);
        jRb_Ventas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRb_Ventas.setText("Ventas");

        bG_Motivo.add(jRb_Muertes);
        jRb_Muertes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRb_Muertes.setText("Muertes");

        bG_Motivo.add(jRb_Perdidas);
        jRb_Perdidas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRb_Perdidas.setText("Pérdidas");

        bG_Motivo.add(jRb_Otros);
        jRb_Otros.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRb_Otros.setText("Otros");

        jLb_ingPor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLb_ingPor.setText("Egreso por");

        bG_Ingreso.add(jRb_Archivo);
        jRb_Archivo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRb_Archivo.setText("Archivo .txt");
        jRb_Archivo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRb_ArchivoStateChanged(evt);
            }
        });
        jRb_Archivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRb_ArchivoActionPerformed(evt);
            }
        });

        bG_Ingreso.add(jRb_Manual);
        jRb_Manual.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRb_Manual.setText("Manual");
        jRb_Manual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRb_ManualActionPerformed(evt);
            }
        });

        jBt_Ingresar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBt_Ingresar.setText("Confirmar");
        jBt_Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt_IngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 100, Short.MAX_VALUE)
                        .addComponent(jLb_Titulo)
                        .addGap(204, 204, 204))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLb_motivo)
                                .addGap(83, 83, 83)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRb_Muertes)
                                    .addComponent(jRb_Ventas)
                                    .addComponent(jRb_Perdidas)
                                    .addComponent(jRb_Otros)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLb_ingPor)
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRb_Manual)
                                    .addComponent(jRb_Archivo))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBt_Ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLb_Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLb_motivo)
                    .addComponent(jRb_Ventas, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jRb_Muertes, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jRb_Perdidas, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jRb_Otros, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLb_ingPor)
                    .addComponent(jRb_Archivo))
                .addGap(18, 18, 18)
                .addComponent(jRb_Manual)
                .addGap(44, 44, 44)
                .addComponent(jBt_Ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        jPanel1.setBounds(0, 0, 690, 470);
        panelEnCapas.add(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEnCapas, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelEnCapas, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRb_ArchivoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRb_ArchivoStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_jRb_ArchivoStateChanged

    private void jRb_ArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRb_ArchivoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jRb_ArchivoActionPerformed

    private void jRb_ManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRb_ManualActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jRb_ManualActionPerformed

    private void jBt_IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt_IngresarActionPerformed
        // TODO add your handling code here:
        ButtonModel bm = this.bG_Motivo.getSelection();
        
        if(bm!=null){
            if(this.jRb_Manual.isSelected()) // Si es ingreso manual, pasa a la pantalla solicitando los datos
            {
                getPanelInterno2().setFormato();
                panelSuperior(getPanelInterno2());
            }else
            {
                boolean ok =false;
                if(this.jRb_Archivo.isSelected())
                {                

                    try {
                        File archivo2 = fileChooser.abrirArchivo();
                        if(archivo2!=null){
                            Utilitario.mensajeProcedimientoCorrecto("Se realizo el egreso de las caravanas correctamente", "Egreso de Caravanas");
                            //this.dispose();
                            ok = true;
                        }
                    } catch (InputMismatchException e) {
                        Utilitario.mensajeError("Archivo seleccionado no pudo ser encontrado.", "ERROR");
                    }catch (Exception exc){
                        Utilitario.mensajeError(exc.toString(),"ERROR");

                    }
                }
                if(ok){
                    getPanelInterno2().setFormato();
                    panelSuperior(getPanelInterno2());
                }
            }
        }else{
            Utilitario.mensajeError("Debe seleccionar un motivo.", "ERROR");
        }
        
    }//GEN-LAST:event_jBt_IngresarActionPerformed

    public void panelSuperior(javax.swing.JPanel panel){
        setPnlAnterior((JPanel) getPanelEnCapas().getComponent(0));
        getPanelEnCapas().moveToBack(getPnlAnterior());
        getPnlAnterior().setVisible(false);

        getPanelEnCapas().moveToFront(panel);
        panel.setVisible(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bG_Ingreso;
    private javax.swing.ButtonGroup bG_Motivo;
    private javax.swing.JButton jBt_Ingresar;
    private javax.swing.JLabel jLb_Titulo;
    private javax.swing.JLabel jLb_ingPor;
    private javax.swing.JLabel jLb_motivo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRb_Archivo;
    private javax.swing.JRadioButton jRb_Manual;
    private javax.swing.JRadioButton jRb_Muertes;
    private javax.swing.JRadioButton jRb_Otros;
    private javax.swing.JRadioButton jRb_Perdidas;
    private javax.swing.JRadioButton jRb_Ventas;
    private javax.swing.JLayeredPane panelEnCapas;
    // End of variables declaration//GEN-END:variables

    
    private IUMenuPrincipal panelPrincipal;  
    private jPEgreso2 panelInterno2;
    private FileChooser fileChooser;
    private javax.swing.JPanel pnlAnterior;

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }    
    
    public IUMenuPrincipal getPanelPrincipal() {
        return panelPrincipal;
    }

    public void setPanelPrincipal(IUMenuPrincipal panelPrincipal) {
        this.panelPrincipal = panelPrincipal;
    }
    public jPEgreso2 getPanelInterno2() {
        return panelInterno2;
    }
    public ButtonGroup getbG_Ingreso() {
        return bG_Ingreso;
    }

    public ButtonGroup getbG_Motivo() {
        return bG_Motivo;
    }
    public void setPanelInterno1(jPEgreso2 panelInterno1) {
        this.panelInterno2 = panelInterno1;
    }
        public JPanel getPnlAnterior() {
        return pnlAnterior;
    }

    public void setPnlAnterior(JPanel pnlAnterior) {
        this.pnlAnterior = pnlAnterior;
    }

    public JLayeredPane getPanelEnCapas() {
        return panelEnCapas;
    }

    public void setPanelEnCapas(JLayeredPane panelEnCapas) {
        this.panelEnCapas = panelEnCapas;
    }

}
