/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package protoipo.UI;

import Fachada.Fachada;
import java.io.File;
import java.util.InputMismatchException;
import javax.swing.ButtonModel;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;
import prototipo.Utilitario.FileChooser;
import prototipo.Utilitario.Utilitario;

/**
 *
 * @author Usuario
 */
public class IUIngreso extends javax.swing.JInternalFrame {

    /**
     * Creates new form IUIngreso
     */
    private Fachada fachada = null;
    public IUIngreso(IUMenuPrincipal principal,Fachada pFachada) {
        super("", true,true,false,true);
        panelPrincipal = principal;
        fachada = pFachada; 
        initComponents();        
        fileChooser = new FileChooser();
        
        panelInterno2 = new jPIngreso2(this,fachada);
        panelInterno2.setBackground(new java.awt.Color(255, 255, 255));
        panelInterno2.setBounds(0, 0, 690, 470);
        panelEnCapas.add(panelInterno2);
        panelEnCapas.moveToBack(panelInterno2);
        panelInterno2.setVisible(false);
        
        panelIngresoD = new jPIngresoD(this,fachada);
        panelIngresoD.setBackground(new java.awt.Color(255, 255, 255));
        panelIngresoD.setBounds(0, 0, 714, 534);
        panelEnCapas.add(panelIngresoD);
        panelEnCapas.moveToBack(panelIngresoD);
        panelIngresoD.setVisible(false);
    }


    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGr_Motivo = new javax.swing.ButtonGroup();
        bGr_Ingreso = new javax.swing.ButtonGroup();
        panelEnCapas = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jLbl_titulo = new javax.swing.JLabel();
        jLb_motivo = new javax.swing.JLabel();
        jRb_Nac = new javax.swing.JRadioButton();
        jRb_Com = new javax.swing.JRadioButton();
        jRb_Otros = new javax.swing.JRadioButton();
        jRb_Archivo = new javax.swing.JRadioButton();
        jLb_ingPor = new javax.swing.JLabel();
        jRb_Archivo1 = new javax.swing.JRadioButton();
        jBt_Ingresar = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLbl_titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLbl_titulo.setForeground(new java.awt.Color(51, 0, 204));
        jLbl_titulo.setText("INGRESO DE CARAVANAS");

        jLb_motivo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLb_motivo.setText("Motivo");

        bGr_Motivo.add(jRb_Nac);
        jRb_Nac.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRb_Nac.setText("Nacimientos");

        bGr_Motivo.add(jRb_Com);
        jRb_Com.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRb_Com.setText("Compras");

        bGr_Motivo.add(jRb_Otros);
        jRb_Otros.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRb_Otros.setText("Otros");

        bGr_Ingreso.add(jRb_Archivo);
        jRb_Archivo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRb_Archivo.setText("Archivo .txt");
        jRb_Archivo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRb_ArchivoStateChanged(evt);
            }
        });
        jRb_Archivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRb_ArchivoActionPerformed(evt);
            }
        });

        jLb_ingPor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLb_ingPor.setText("Ingreso por");

        bGr_Ingreso.add(jRb_Archivo1);
        jRb_Archivo1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRb_Archivo1.setText("Manual");
        jRb_Archivo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRb_Archivo1ActionPerformed(evt);
            }
        });

        jBt_Ingresar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBt_Ingresar.setText("Confirmar");
        jBt_Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt_IngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jLbl_titulo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBt_Ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLb_ingPor)
                                    .addComponent(jLb_motivo))
                                .addGap(54, 54, 54)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRb_Archivo1)
                                    .addComponent(jRb_Archivo)
                                    .addComponent(jRb_Nac)
                                    .addComponent(jRb_Com)
                                    .addComponent(jRb_Otros))
                                .addGap(242, 242, 242)))))
                .addGap(101, 101, 101))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLbl_titulo)
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRb_Nac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLb_motivo))
                .addGap(18, 18, 18)
                .addComponent(jRb_Com, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jRb_Otros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLb_ingPor)
                    .addComponent(jRb_Archivo))
                .addGap(18, 18, 18)
                .addComponent(jRb_Archivo1)
                .addGap(63, 63, 63)
                .addComponent(jBt_Ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        jPanel1.setBounds(0, 0, 700, 500);
        panelEnCapas.add(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEnCapas, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelEnCapas, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRb_ArchivoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRb_ArchivoStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_jRb_ArchivoStateChanged

    private void jRb_ArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRb_ArchivoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jRb_ArchivoActionPerformed

    private void jRb_Archivo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRb_Archivo1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jRb_Archivo1ActionPerformed

    private void jBt_IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt_IngresarActionPerformed
        // TODO add your handling code here:
        ButtonModel bm = this.bGr_Motivo.getSelection();
        if(bm!=null){
            if(this.jRb_Archivo1.isSelected()) // Si es ingreso manual, pasa a la pantalla solicitando los datos
            {
                panelSuperior(getPanelInterno2());
            }else
            {
                boolean ok =false;
                if(this.jRb_Archivo.isSelected())
                {
                    
                    try {
                        File archivo = fileChooser.abrirArchivo();
                        if(archivo!=null){
                            Utilitario.mensajeProcedimientoCorrecto("Se realizo el ingreso de las caravanas correctamente", "Ingreso de Caravanas");
                            //this.dispose();
                            ok = true;
                        }
                    } catch (InputMismatchException e) {
                        Utilitario.mensajeError("Archivo seleccionado no pudo ser encontrado.", "ERROR");
                    }catch (Exception exc){
                        Utilitario.mensajeError(exc.toString(),"ERROR");
                    }
                }
                if(ok){
                    getPanelIngresoD().actualizar();
                    panelSuperior(getPanelIngresoD());;
                }
            }            
        }else{
            Utilitario.mensajeError("Debe seleccionar un motivo.", "ERROR");
        }
    }//GEN-LAST:event_jBt_IngresarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bGr_Ingreso;
    private javax.swing.ButtonGroup bGr_Motivo;
    private javax.swing.JButton jBt_Ingresar;
    private javax.swing.JLabel jLb_ingPor;
    private javax.swing.JLabel jLb_motivo;
    private javax.swing.JLabel jLbl_titulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRb_Archivo;
    private javax.swing.JRadioButton jRb_Archivo1;
    private javax.swing.JRadioButton jRb_Com;
    private javax.swing.JRadioButton jRb_Nac;
    private javax.swing.JRadioButton jRb_Otros;
    private javax.swing.JLayeredPane panelEnCapas;
    // End of variables declaration//GEN-END:variables
    
    private IUMenuPrincipal panelPrincipal;
    private FileChooser fileChooser;
    private javax.swing.JPanel pnlAnterior;
    private jPIngreso2 panelInterno2;
    private jPIngresoD panelIngresoD;
    
    
    public void panelSuperior(javax.swing.JPanel panel){
        setPnlAnterior((JPanel) getPanelEnCapas().getComponent(0));
        getPanelEnCapas().moveToBack(getPnlAnterior());
        getPnlAnterior().setVisible(false);

        getPanelEnCapas().moveToFront(panel);
        panel.setVisible(true);
    }
    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }    
    
    public IUMenuPrincipal getPanelPrincipal() {
        return panelPrincipal;
    }

    public void setPanelPrincipal(IUMenuPrincipal panelPrincipal) {
        this.panelPrincipal = panelPrincipal;
    }
    public jPIngreso2 getPanelInterno2() {
        return panelInterno2;
    }

    public void setPanelInterno1(jPIngreso2 panelInterno1) {
        this.panelInterno2 = panelInterno1;
    }
    public jPIngresoD getPanelIngresoD() {
        return panelIngresoD;
    }

    public void setPanelIngresoD(jPIngresoD panelInterno1) {
        this.panelIngresoD = panelInterno1;
    }
    public JPanel getPnlAnterior() {
        return pnlAnterior;
    }

    public void setPnlAnterior(JPanel pnlAnterior) {
        this.pnlAnterior = pnlAnterior;
    }

    public JLayeredPane getPanelEnCapas() {
        return panelEnCapas;
    }

    public void setPanelEnCapas(JLayeredPane panelEnCapas) {
        this.panelEnCapas = panelEnCapas;
    }


}
