/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package protoipo.UI;

import Fachada.Fachada;
import java.awt.Color;
import java.awt.Dialog.ModalExclusionType;
import prototipo.Utilitario.*;

/**
 *
 * @author Usuario
 */
public class IUMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form IUMenuPrincipal
     */
    private IUEgresosC frmEgresos = null;
    private IUIngreso frmIngreso = null;
    private IUBusAni frmBusqueda = null;
    private IUModDatos frmModDatos = null;
    private Fachada fachada = null;
    
    
    public IUMenuPrincipal() {
        fachada = new Fachada();
        // -- CARGA LA IMAGEN --
        PanelImagen fondo  = new PanelImagen(Utilitario.crearIcono("src/prototipo/images/Imagen.jpg", 1000, 600).getImage());
        
                
        initComponents();
        
        //(APPLICATION_EXCLUDE)La ventana que utiliza este valor de enumeracion no será bloqueada 
        //por ningún diálogo de la aplicación. 
        this.setModalExclusionType(ModalExclusionType.APPLICATION_EXCLUDE);
        //this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.setExtendedState(this.MAXIMIZED_BOTH);
       
        //fondo.setBounds(50,50,1000,600);
        this.jp_Foto.setSize(1000, 600);
        this.jp_Foto.add(fondo);   
        
              
    }
    public Fachada getFachada() {
        return fachada;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jp_Menu = new javax.swing.JPanel();
        jbt_IngCar = new javax.swing.JButton();
        jbt_EgrCar = new javax.swing.JButton();
        jbt_TraVet = new javax.swing.JButton();
        jbt_LecCom1 = new javax.swing.JButton();
        jbt_BusAni1 = new javax.swing.JButton();
        jbt_DatMod = new javax.swing.JButton();
        jbt_ModDat = new javax.swing.JButton();
        jbt_Cons = new javax.swing.JButton();
        jp_Foto = new javax.swing.JPanel();
        jd_Panel = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TRAZABILIDAD ANIMAL POR DICOSE FISICO");

        jp_Menu.setBackground(new java.awt.Color(255, 255, 255));

        jbt_IngCar.setBackground(new java.awt.Color(255, 255, 255));
        jbt_IngCar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbt_IngCar.setForeground(new java.awt.Color(51, 0, 204));
        jbt_IngCar.setText("Ingreso de Caravanas");
        jbt_IngCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_IngCarActionPerformed(evt);
            }
        });

        jbt_EgrCar.setBackground(new java.awt.Color(255, 255, 255));
        jbt_EgrCar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbt_EgrCar.setForeground(new java.awt.Color(51, 0, 204));
        jbt_EgrCar.setText("Egreso de Caravanas");
        jbt_EgrCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_EgrCarActionPerformed(evt);
            }
        });

        jbt_TraVet.setBackground(new java.awt.Color(255, 255, 255));
        jbt_TraVet.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbt_TraVet.setForeground(new java.awt.Color(51, 0, 204));
        jbt_TraVet.setText("Tratamientos Veterinarios");
        jbt_TraVet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_TraVetActionPerformed(evt);
            }
        });

        jbt_LecCom1.setBackground(new java.awt.Color(255, 255, 255));
        jbt_LecCom1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbt_LecCom1.setForeground(new java.awt.Color(51, 0, 204));
        jbt_LecCom1.setText("Lectura Comparativa");

        jbt_BusAni1.setBackground(new java.awt.Color(255, 255, 255));
        jbt_BusAni1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbt_BusAni1.setForeground(new java.awt.Color(51, 0, 204));
        jbt_BusAni1.setText("Búsqueda de animales");
        jbt_BusAni1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_BusAni1ActionPerformed(evt);
            }
        });

        jbt_DatMod.setBackground(new java.awt.Color(255, 255, 255));
        jbt_DatMod.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbt_DatMod.setForeground(new java.awt.Color(51, 0, 204));
        jbt_DatMod.setText("Datos pendientes");
        jbt_DatMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_DatModActionPerformed(evt);
            }
        });

        jbt_ModDat.setBackground(new java.awt.Color(255, 255, 255));
        jbt_ModDat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbt_ModDat.setForeground(new java.awt.Color(51, 0, 204));
        jbt_ModDat.setText("Modificación de datos");
        jbt_ModDat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_ModDatActionPerformed(evt);
            }
        });

        jbt_Cons.setBackground(new java.awt.Color(255, 255, 255));
        jbt_Cons.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbt_Cons.setForeground(new java.awt.Color(51, 0, 204));
        jbt_Cons.setText("Consultas");
        jbt_Cons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_ConsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_FotoLayout = new javax.swing.GroupLayout(jp_Foto);
        jp_Foto.setLayout(jp_FotoLayout);
        jp_FotoLayout.setHorizontalGroup(
            jp_FotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jp_FotoLayout.setVerticalGroup(
            jp_FotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 226, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jp_MenuLayout = new javax.swing.GroupLayout(jp_Menu);
        jp_Menu.setLayout(jp_MenuLayout);
        jp_MenuLayout.setHorizontalGroup(
            jp_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jp_Foto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbt_IngCar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbt_EgrCar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbt_TraVet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbt_LecCom1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbt_BusAni1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbt_DatMod, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbt_ModDat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbt_Cons, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jp_MenuLayout.setVerticalGroup(
            jp_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_MenuLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jbt_IngCar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbt_EgrCar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbt_LecCom1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbt_BusAni1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbt_TraVet, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbt_ModDat, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbt_Cons, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbt_DatMod, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jp_Foto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(jp_Menu);

        jd_Panel.setBackground(new java.awt.Color(102, 153, 0));
        jd_Panel.setForeground(new java.awt.Color(153, 153, 0));
        jSplitPane1.setRightComponent(jd_Panel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 714, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbt_TraVetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_TraVetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbt_TraVetActionPerformed

    private void jbt_BusAni1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_BusAni1ActionPerformed
        // TODO add your handling code here:
        if(frmBusqueda == null || frmBusqueda.isClosed()){
            frmBusqueda = new IUBusAni(this,fachada);
            frmBusqueda.setVisible(true);
            this.jd_Panel.add(frmBusqueda, 0);
            this.jd_Panel.getComponent(0).setLocation(50, 50);
        } 
    }//GEN-LAST:event_jbt_BusAni1ActionPerformed

    private void jbt_DatModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_DatModActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbt_DatModActionPerformed

    private void jbt_ModDatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_ModDatActionPerformed
        // TODO add your handling code here:
        if(frmModDatos == null || frmModDatos.isClosed()){
            frmModDatos = new IUModDatos(this,fachada);
            frmModDatos.setVisible(true);
            this.jd_Panel.add(frmModDatos, 0);
            this.jd_Panel.getComponent(0).setLocation(50, 50);
        }
        
        
    }//GEN-LAST:event_jbt_ModDatActionPerformed

    private void jbt_ConsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_ConsActionPerformed
        // TODO add your handling code here:
//        MuestraTabla mt = new MuestraTabla(this);
//        mt.setVisible(true);
//        this.jd_Panel.add(mt, 0);
//        this.jd_Panel.getComponent(0).setLocation(50, 50);
        
    }//GEN-LAST:event_jbt_ConsActionPerformed

    private void jbt_IngCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_IngCarActionPerformed
        // TODO add your handling code here:        
        if(frmIngreso == null || frmIngreso.isClosed()){
            frmIngreso = new IUIngreso(this,getFachada());
            frmIngreso.setVisible(true);        
            this.jd_Panel.add(frmIngreso, 0);
            this.jd_Panel.getComponent(0).setLocation(50, 50);
        }        
    }//GEN-LAST:event_jbt_IngCarActionPerformed

    private void jbt_EgrCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_EgrCarActionPerformed
        // TODO add your handling code here:
        if(frmEgresos == null || frmEgresos.isClosed()){
            frmEgresos = new IUEgresosC(this,fachada);
            frmEgresos.setVisible(true);
            this.jd_Panel.add(frmEgresos, 0);
            this.jd_Panel.getComponent(0).setLocation(50, 50);
        }  
        
        
    }//GEN-LAST:event_jbt_EgrCarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IUMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IUMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IUMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IUMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IUMenuPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton jbt_BusAni1;
    private javax.swing.JButton jbt_Cons;
    private javax.swing.JButton jbt_DatMod;
    private javax.swing.JButton jbt_EgrCar;
    private javax.swing.JButton jbt_IngCar;
    private javax.swing.JButton jbt_LecCom1;
    private javax.swing.JButton jbt_ModDat;
    private javax.swing.JButton jbt_TraVet;
    private javax.swing.JDesktopPane jd_Panel;
    private javax.swing.JPanel jp_Foto;
    private javax.swing.JPanel jp_Menu;
    // End of variables declaration//GEN-END:variables
}
