/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package protoipo.UI;

import Fachada.Fachada;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.ButtonModel;
import javax.swing.JTextField;
import prototipo.Utilitario.Utilitario;

/**
 *
 * @author Deibys
 */
public class jPEgreso2 extends javax.swing.JPanel {

    /**
     * Creates new form jPEgreso2
     */
    private Fachada fachada = null;
    String jrbText = null;
    public jPEgreso2(IUEgresosC principalEgresos,Fachada pFachada) {
        initComponents();
        this.setPrincipalEgreso(principalEgresos);
        fachada = pFachada;
        esconderCampos();

    }

    public void setFormato() {
        jrbText = "";
        Enumeration elements = getPrincipalEgreso().getbG_Motivo().getElements();
        while (elements.hasMoreElements()) {
            AbstractButton button = (AbstractButton) elements.nextElement();
            if (button.isSelected()) {
                jrbText = button.getText();
            }
        }
        esconderCampos();
        if (jrbText.equals("Ventas")) {
            this.jLbl_Motivo.setText(jrbText + ".");
            motivoVentas();
        } else if (jrbText.equals("Muertes")) {
            this.jLbl_Motivo.setText(jrbText + ".");
            motivoMuertes();
        } else if (jrbText.equals("Pérdidas")) {
            this.jLbl_Motivo.setText(jrbText + ".");
        } else if (jrbText.equals("Otros")) {
            this.jLbl_Motivo.setText(jrbText + ".");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLb_Titulo = new javax.swing.JLabel();
        jLb_Caravana = new javax.swing.JLabel();
        jTF_Caravana = new javax.swing.JTextField();
        jLbl_Motivo = new javax.swing.JLabel();
        jBtn_Volver = new javax.swing.JButton();
        jLb_Guia = new javax.swing.JLabel();
        jLb_GuiaSerie = new javax.swing.JLabel();
        jLb_GuiaNumero = new javax.swing.JLabel();
        jTF_GuiaSerie = new javax.swing.JTextField();
        jTF_GuiaNumero = new javax.swing.JTextField();
        jLb_Destino = new javax.swing.JLabel();
        jTF_Destino = new javax.swing.JTextField();
        jBtn_Confirmar = new javax.swing.JButton();
        jDC_Fecha = new com.toedter.calendar.JDateChooser();
        jLb_Fecha = new javax.swing.JLabel();

        jLb_Titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLb_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLb_Titulo.setText("EGRESO DE CARAVANAS");

        jLb_Caravana.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLb_Caravana.setText("Caravana");

        jTF_Caravana.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTF_Caravana.setMinimumSize(new java.awt.Dimension(6, 200));
        jTF_Caravana.setPreferredSize(new java.awt.Dimension(6, 20));

        jLbl_Motivo.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLbl_Motivo.setText("...");

        jBtn_Volver.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtn_Volver.setText("Volver");
        jBtn_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_VolverActionPerformed(evt);
            }
        });

        jLb_Guia.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLb_Guia.setText("Guía");

        jLb_GuiaSerie.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLb_GuiaSerie.setText("Serie");

        jLb_GuiaNumero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLb_GuiaNumero.setText("Número");

        jTF_GuiaSerie.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTF_GuiaNumero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLb_Destino.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLb_Destino.setText("Dicose B");

        jTF_Destino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jBtn_Confirmar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtn_Confirmar.setText("Confirmar");
        jBtn_Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_ConfirmarActionPerformed(evt);
            }
        });

        jDC_Fecha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLb_Fecha.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLb_Fecha.setText("Fecha");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLb_Caravana)
                    .addComponent(jLb_Guia)
                    .addComponent(jLb_Destino)
                    .addComponent(jBtn_Volver)
                    .addComponent(jLb_Fecha))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtn_Confirmar)
                        .addGap(135, 135, 135))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTF_Caravana, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTF_Destino, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLb_GuiaSerie)
                                                .addComponent(jTF_GuiaSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLb_GuiaNumero)
                                                .addComponent(jTF_GuiaNumero))))
                                    .addGap(1, 1, 1)))
                            .addComponent(jDC_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLbl_Motivo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLb_Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
                        .addGap(90, 90, 90))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLb_Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLbl_Motivo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLb_GuiaSerie)
                    .addComponent(jLb_GuiaNumero))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTF_GuiaSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTF_GuiaNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLb_Guia))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLb_Destino)
                            .addComponent(jTF_Destino, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(jDC_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLb_Fecha)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTF_Caravana, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLb_Caravana, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(135, 135, 135)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn_Volver)
                    .addComponent(jBtn_Confirmar))
                .addGap(37, 37, 37))
        );

        jLbl_Motivo.getAccessibleContext().setAccessibleName("jLblMotivo");
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_VolverActionPerformed
        // TODO add your handling code here:
        getPrincipalEgreso().panelSuperior(getPrincipalEgreso().getPnlAnterior());
    }//GEN-LAST:event_jBtn_VolverActionPerformed

    private void jBtn_ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_ConfirmarActionPerformed
        // TODO add your handling code here:
        String formato = "dd/MM/yyyy";      //Formato de la fecha
        String parametro = jrbText+ ";" ;
        boolean procesoOK = false;
        if (jrbText.equals("Ventas")) {       
            parametro += jTF_GuiaSerie.getText()+ ";" +jTF_GuiaNumero.getText() + 
                    ";" + jTF_Caravana.getText()+ ";" + jTF_Destino.getText()+ ";";
            
            Date date = jDC_Fecha.getDate();
            SimpleDateFormat sdf = new SimpleDateFormat(formato);
            parametro += sdf.format(date);
            
            if(fachada.procesaEgresoManual(parametro)) procesoOK=true;
        } else if (jrbText.equals("Muertes")) {
            parametro +=  jTF_Caravana.getText()+ ";";
            Date date = jDC_Fecha.getDate();
            SimpleDateFormat sdf = new SimpleDateFormat(formato);
            parametro += sdf.format(date);
            if(fachada.procesaEgresoManual(parametro)) procesoOK=true;
        } else if (jrbText.equals("Pérdidas")) {
            this.jLbl_Motivo.setText(jrbText + ".");
        } else if (jrbText.equals("Otros")) {
            this.jLbl_Motivo.setText(jrbText + ".");
        }
        if(procesoOK){
            inicializarP();
            Utilitario.mensajeProcedimientoCorrecto("Se realizo el egreso correctamente", "Egreso de Animal");
        }else{
            Utilitario.mensajeError("No se realizo el egreso", "Egreso de Animal");
        }
        
    }//GEN-LAST:event_jBtn_ConfirmarActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_Confirmar;
    private javax.swing.JButton jBtn_Volver;
    private com.toedter.calendar.JDateChooser jDC_Fecha;
    private javax.swing.JLabel jLb_Caravana;
    private javax.swing.JLabel jLb_Destino;
    private javax.swing.JLabel jLb_Fecha;
    private javax.swing.JLabel jLb_Guia;
    private javax.swing.JLabel jLb_GuiaNumero;
    private javax.swing.JLabel jLb_GuiaSerie;
    private javax.swing.JLabel jLb_Titulo;
    private javax.swing.JLabel jLbl_Motivo;
    private javax.swing.JTextField jTF_Caravana;
    private javax.swing.JTextField jTF_Destino;
    private javax.swing.JTextField jTF_GuiaNumero;
    private javax.swing.JTextField jTF_GuiaSerie;
    // End of variables declaration//GEN-END:variables

    
    private IUEgresosC principalEgreso;
    
    public JTextField getjTF_Caravana() {
        return jTF_Caravana;
    }
    public IUEgresosC getPrincipalEgreso() {
        return principalEgreso;
    }

    public void setPrincipalEgreso(IUEgresosC principalEgreso) {
        this.principalEgreso = principalEgreso;
    }

    private void esconderCampos() {
        jLb_Guia.setVisible(false);
        jLb_GuiaNumero.setVisible(false);
        jLb_GuiaSerie.setVisible(false);
        jTF_GuiaNumero.setVisible(false);
        jTF_GuiaSerie.setVisible(false);
        jLb_Caravana.setVisible(false);
        jTF_Caravana.setVisible(false);
        jLb_Destino.setVisible(false);
        jTF_Destino.setVisible(false);
        jLb_Fecha.setVisible(false);
        jDC_Fecha.setVisible(false);

    }

    public void motivoVentas() {
        jLb_Guia.setVisible(true);
        jLb_GuiaNumero.setVisible(true);
        jLb_GuiaSerie.setVisible(true);
        jTF_GuiaNumero.setVisible(true);
        jTF_GuiaSerie.setVisible(true);
        jLb_Caravana.setVisible(true);
        jTF_Caravana.setVisible(true);
        jLb_Destino.setVisible(true);
        jTF_Destino.setVisible(true);
        jLb_Fecha.setVisible(true);
        jDC_Fecha.setVisible(true);
    }

    public void motivoMuertes() {
        jLb_Fecha.setVisible(true);
        jDC_Fecha.setVisible(true);
        jLb_Caravana.setVisible(true);
        jTF_Caravana.setVisible(true);
    }

    public void motivoPérdidas() {
    }

    public void motivoOtros() {
    }

    private void inicializarP() {

        jTF_GuiaNumero.setText("");
        jTF_GuiaSerie.setText("");
        jTF_Caravana.setText("");
        jTF_Destino.setText("");
        jLb_Fecha.setText("");

    }
}
