/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package protoipo.UI;

import Fachada.Fachada;
import java.awt.Component;
import javax.swing.JComboBox;
import prototipo.Utilitario.Utilitario;

/**
 *
 * @author Usuario
 */
public class jPIngreso2 extends javax.swing.JPanel {

    /**
     * Creates new form jPIngreso2
     */
    private IUIngreso principal;
    private Fachada fachada = null;
    public jPIngreso2(IUIngreso unPrincipal, Fachada pFachada) {
        principal = unPrincipal;
        fachada = pFachada;
        initComponents();
        cargaCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLbl_titulo = new javax.swing.JLabel();
        btn_Salir = new javax.swing.JButton();
        jLb_Proper = new javax.swing.JLabel();
        jLb_Sexo = new javax.swing.JLabel();
        jLb_Raza = new javax.swing.JLabel();
        jLb_Nacimiento = new javax.swing.JLabel();
        jLb_Campo = new javax.swing.JLabel();
        jLb_Traz = new javax.swing.JLabel();
        jTF_Proper = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jTF_Nac_Mes = new javax.swing.JTextField();
        jTF_Nac_Anio = new javax.swing.JTextField();
        jTF_Campo = new javax.swing.JTextField();
        jTF_Traza = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        jBt_Ingresar1 = new javax.swing.JButton();
        jLb_Cat = new javax.swing.JLabel();
        jCmb_Cat = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(255, 255, 255));

        jLbl_titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLbl_titulo.setForeground(new java.awt.Color(51, 0, 204));
        jLbl_titulo.setText("INGRESO DE ANIMAL");

        btn_Salir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Salir.setText("Salir");
        btn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalirActionPerformed(evt);
            }
        });

        jLb_Proper.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLb_Proper.setText("Propietario");

        jLb_Sexo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLb_Sexo.setText("Sexo");

        jLb_Raza.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLb_Raza.setText("Raza");

        jLb_Nacimiento.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLb_Nacimiento.setText("Nacimiento");

        jLb_Campo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLb_Campo.setText("Campo");

        jLb_Traz.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLb_Traz.setText("Trazabilidad");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Macho", "Hembra" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hereford", "Aberdeen", "Limousine", "Normando", "Holando", "Brackford", "Brangus" }));

        jBt_Ingresar1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBt_Ingresar1.setText("Confirmar");
        jBt_Ingresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt_Ingresar1ActionPerformed(evt);
            }
        });

        jLb_Cat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLb_Cat.setText("Categoria");

        jCmb_Cat.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Terneras", "Terneros", "Vaquillona de 1 a 2", "Vaquillona de 2 a 3", "Vaca de Cría", "Vaca de Invernada", "Novillos de 1 a 2", "Novillos de 2 a 3", "Novillos mas de 3", "Toros" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLbl_titulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLb_Proper)
                            .addComponent(jLb_Sexo)
                            .addComponent(jLb_Raza)
                            .addComponent(jLb_Nacimiento)
                            .addComponent(jLb_Campo)
                            .addComponent(jLb_Traz)
                            .addComponent(jLb_Cat))
                        .addGap(132, 132, 132)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTF_Traza, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(jTF_Proper, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jTF_Nac_Mes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTF_Nac_Anio, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTF_Campo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(jCmb_Cat, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(175, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(426, Short.MAX_VALUE)
                    .addComponent(jBt_Ingresar1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(165, 165, 165)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLbl_titulo)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLb_Proper)
                    .addComponent(jTF_Proper, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLb_Sexo)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLb_Raza)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLb_Nacimiento)
                    .addComponent(jTF_Nac_Mes, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTF_Nac_Anio, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLb_Cat)
                    .addComponent(jCmb_Cat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF_Traza, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLb_Campo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLb_Traz)
                    .addComponent(jTF_Campo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(btn_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(466, Short.MAX_VALUE)
                    .addComponent(jBt_Ingresar1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(33, 33, 33)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalirActionPerformed
        // TODO add your handling code here:

        this.principal.dispose();
    }//GEN-LAST:event_btn_SalirActionPerformed

    private void jBt_Ingresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt_Ingresar1ActionPerformed
        // TODO add your handling code here:
        
        inicializarP();
        Utilitario.mensajeProcedimientoCorrecto("Se realizo el ingreso correctamente", "Ingreso de Animal");
               
    }//GEN-LAST:event_jBt_Ingresar1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        this.cargaCombo();
    }//GEN-LAST:event_jComboBox1ActionPerformed
    public void inicializarP()
    {        
        jTF_Campo.setText("");
        jTF_Nac_Anio.setText("");
        jTF_Nac_Mes.setText("");
        jTF_Proper.setText("");
        jTF_Traza.setText("");
        jComboBox2.setSelectedIndex(0);
    
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Salir;
    private javax.swing.JButton jBt_Ingresar1;
    private javax.swing.JComboBox jCmb_Cat;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLb_Campo;
    private javax.swing.JLabel jLb_Cat;
    private javax.swing.JLabel jLb_Nacimiento;
    private javax.swing.JLabel jLb_Proper;
    private javax.swing.JLabel jLb_Raza;
    private javax.swing.JLabel jLb_Sexo;
    private javax.swing.JLabel jLb_Traz;
    private javax.swing.JLabel jLbl_titulo;
    private javax.swing.JTextField jTF_Campo;
    private javax.swing.JTextField jTF_Nac_Anio;
    private javax.swing.JTextField jTF_Nac_Mes;
    private javax.swing.JTextField jTF_Proper;
    private javax.swing.JTextField jTF_Traza;
    // End of variables declaration//GEN-END:variables
 
    
    public void cargaCombo()
    {
        this.jCmb_Cat.removeAllItems();
        if(this.jComboBox1.getSelectedIndex() == 0)
        {
            this.jCmb_Cat.addItem("Terneros");
            this.jCmb_Cat.addItem("Novillos de 1 a 2");
            this.jCmb_Cat.addItem("Novillos de 2 a 3");
            this.jCmb_Cat.addItem("Novillos mas de 3");
            this.jCmb_Cat.addItem("Toros");        
        }
        else
        {
            this.jCmb_Cat.addItem("Terneras");
            this.jCmb_Cat.addItem("Vaquillona de 1 a 2");
            this.jCmb_Cat.addItem("Vaquillona de 2 a 3");
            this.jCmb_Cat.addItem("Vaca de Cría");
            this.jCmb_Cat.addItem("Vaca de Invernada");
        }
    }
}
