/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package protoipo.UI;

import Fachada.Fachada;
import java.awt.BorderLayout;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import prototipo.Utilitario.Utilitario;

/**
 *
 * @author Usuario
 */
public class jPIngresoD extends javax.swing.JPanel {

    /**
     * Creates new form jPIngresoD
     */
    private IUIngreso principal;
    private Fachada fachada = null;
    private JTable jTblIngreso2;
    
    public jPIngresoD(IUIngreso unPrincipal, Fachada pFachada) {
        principal = unPrincipal;
        fachada = pFachada;
        
        initComponents();
        //cargaTabla();
    }
    public void cargaTabla(){
        Object[][] datos = obtenerDatosParaTabla();
        String[] nomCol = obtenerNombresDeColumnas();     
        
        jTblIngreso2 = new JTable(datos,nomCol); 
        jScrollPane1.setViewportView(jTblIngreso2);
           
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLbl_titulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblIngreso = new javax.swing.JTable();
        jBt_Ingresar = new javax.swing.JButton();
        jBt_Volver = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(713, 534));

        jLbl_titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLbl_titulo.setForeground(new java.awt.Color(51, 0, 204));
        jLbl_titulo.setText("INGRESO DETALLE DE ANIMALES");

        jTblIngreso.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTblIngreso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Trazabilidad", "Propietario", "Sexo", "Nacimiento", "Campo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTblIngreso);

        jBt_Ingresar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBt_Ingresar.setText("Confirmar");
        jBt_Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt_IngresarActionPerformed(evt);
            }
        });

        jBt_Volver.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBt_Volver.setText("Volver");
        jBt_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBt_VolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jBt_Ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBt_Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(jLbl_titulo)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLbl_titulo)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBt_Ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBt_Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBt_IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt_IngresarActionPerformed
        // TODO add your handling code here:
        
           Utilitario.mensajeProcedimientoCorrecto("Se realizó el ingreso correctamente", "Ingreso de Caravanas");
           principal.dispose();
        
    }//GEN-LAST:event_jBt_IngresarActionPerformed

    private void jBt_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBt_VolverActionPerformed
        // TODO add your handling code here:
        
        principal.panelSuperior(principal.getPnlAnterior());

    }//GEN-LAST:event_jBt_VolverActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBt_Ingresar;
    private javax.swing.JButton jBt_Volver;
    private javax.swing.JLabel jLbl_titulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblIngreso;
    // End of variables declaration//GEN-END:variables

    private Object[][] obtenerDatosParaTabla() {
         Object[][] data = {
            {new Integer(100020), new Integer(112233), "Hembra", "20/02/2013", "14"},
            {new Integer(100021), new Integer(112233), "Macho", "20/02/2013", "15"},
            {new Integer(100022), new Integer(112233), "Macho", "20/02/2013", "14"},
            {new Integer(100023), new Integer(112233), "Hembra", "20/02/2013", "14"},
            {new Integer(100024), new Integer(112233), "Macho", "20/02/2013", "14"}
        };
        return data;
    }
    private String[] obtenerNombresDeColumnas(){
        String[] nombresColumnas = {"Trazabilidad", "Propietario", "Sexo", "Nacimiento", "Campo"};
        return nombresColumnas;
    }

    public void actualizar() {
        cargaTabla();  
    
    }
}
